In [33]:
import pandas as pd
import numpy as np

In [34]:
ratings = {
    "2u7T5g3WNhXLNt8eXLm7iYrvR872": 0,
    "3mHQgTNdhoXXOWEsJmHvbBuOxSb2": 3,
    "4jQ4QWrm9SOsFMLIAajSZ5Usva82": 3,
    "5HBSsBrc7LSwIQyRgTqY7Zf641f2": 3,
    "7atSgfmCF7ZvgnM9qSbSoEFikfD2": 4,
    "9IRzXasJsgMDJgRKZg53Hhc9Uti1": 3,
    "EbpGnYMAbwSEXjZdZjScjd24CHi1": 2,
    "Jewf7XHNHFgjJzxSWPEHVgTF6ra2": 1,
    "JiwrisF5l4QrhHXCKj90Qk2032G2": 4,
    "KhANCE2HhQSqQNd0HJm5yVyS7st1": 1,
    "MeLjXyToMNQEWRYBnoUBbpbAt7C3": 2,
    "NYUd8KmmZfaJSr1oYTBt0y5Gsbl2": 3,
    "O5lwXKqlL2UuYGzxaPSSe7W8C5a2": 1,
    "P5RrHrryYuZXtE1QNzKDI0jtpqS2": 1,
    "P7ZnBWM7uuVkKncJrXjXLwE8jqd2": 1,
    "Pb1MbD8CBwTZ6qcjCb6BYTVutzI2": 0,
    "QRngP1wkY3a1WZl5gYR6qIF6lPj2": 1,
    "RNqrJKIl9pQvsobA8LDjExiO1h03": 2,
    "S6mTOBRCjmPpquYEDPO62ND3afg1": 2,
    "SPpu1fxdZmWB5jNCNjYrGhucjAL2": 2,
    "VFoVWtjLdXZZIejvwMN2J5zEcVO2": 2,
    "VItmCCypvlW9IGOONV6O6CoBBD33": 2,
    "VZBsnBF2obMyB36aZ3wzpKcucOl2": 1,
    "VaT8h1PGCAWfWfzcG5fZW2xucmf2": 3,
    "VcePEOBnxcMeFUjuqM2K2OIsABB3": 3,
    "W2mJKB5gljZdR8gAmpAANCoNQBH2": 0,
    "X7gEBonEbOPNxi6oFKeLrohKUfm2": 3,
    "aVeHsZYwcfc9eCoptpmrL5u6Yd43": 4,
    "bZWwLWJAF7WGlQrekXNN7CTY8nw1": 0,
    "bdKEdkTKDKY4LMXOx7SzaXPQYCV2": 2,
    "cY7XsBMBcfZ0R75OQLiasvzS4bC3": 1,
    "eIop89H3jLMR8hyKzDhCvQSNwFc2": 1,
    "edwmE4aFFtRQfYX1RzNbumGVbok1": 4,
    "jbm4Isok8iU3ygjXAzIEeTbVHVm2": 4,
    "lOD8oE1MURdtuww0e4TCOhWy3S72": 0,
    "nquOc0pqXQUCryATzculHkzHB9U2": 4,
    "qltYUsax52W1myQZPSoqzowz83S2": 2,
    "r5D2dMvmo3WmhAgA03if57j4z452": 0,
    "svgyp5e21pbsS0930QgkvdK923a2": 3,
    "u9ME9uQr7cPierYMXJwmWXjXCK33": 0,
    "umfcis3qbCWhlqndqYRkIXP4oWo1": 3,
    "uxuLXvSMSvbzSLk7tCHFz93jwbp1": 1,
    "wgMaiRnhTxZ3vv8Ak0k4NTfCf9g2": 0,
    "xMSoAclXQHUWstVzId3JCanXLTz2": 1,
    "zMvFhfdZpEfefExVpmh3pAE2rS82": 3
}

In [35]:
len(ratings)

45

In [36]:
ratings_df = pd.read_csv('ratings.csv')
ratings_df.head()

,user_hash,0071.jpg,0351.jpg,0428.jpg,0546.jpg,0001.jpg,0290.jpg,0527.jpg,0054.jpg,0652.jpg,...,0636.jpg,0409.jpg,0315.jpg,0741.jpg,0356.jpg,0650.jpg,0535.jpg,0382.jpg,0611.jpg,0128.jpg
0,2u7T5g3WNhXLNt8eXLm7iYrvR872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2u7T5g3WNhXLNt8eXLm7iYrvR872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2u7T5g3WNhXLNt8eXLm7iYrvR872,4.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2u7T5g3WNhXLNt8eXLm7iYrvR872,NaN,NaN,5.0,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2u7T5g3WNhXLNt8eXLm7iYrvR872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
ratings_df['user_hash'].nunique()

51

In [38]:
ratings_df = ratings_df.groupby('user_hash').max()
ratings_df.head()

,0071.jpg,0351.jpg,0428.jpg,0546.jpg,0001.jpg,0290.jpg,0527.jpg,0054.jpg,0652.jpg,0164.jpg,...,0636.jpg,0409.jpg,0315.jpg,0741.jpg,0356.jpg,0650.jpg,0535.jpg,0382.jpg,0611.jpg,0128.jpg
user_hash,,,,,,,,,,,,,,,,,,,,,
2u7T5g3WNhXLNt8eXLm7iYrvR872,4.0,5.0,5.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3mHQgTNdhoXXOWEsJmHvbBuOxSb2,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4jQ4QWrm9SOsFMLIAajSZ5Usva82,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5HBSsBrc7LSwIQyRgTqY7Zf641f2,1.0,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69AHmihCRKbJbXXM9GQ4FT7NSU32,5.0,4.0,2.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
ratings_df.dropna(inplace=True, how='all')
ratings_df.replace(np.nan, 0, inplace=True)
ratings_df.head()

,0071.jpg,0351.jpg,0428.jpg,0546.jpg,0001.jpg,0290.jpg,0527.jpg,0054.jpg,0652.jpg,0164.jpg,...,0636.jpg,0409.jpg,0315.jpg,0741.jpg,0356.jpg,0650.jpg,0535.jpg,0382.jpg,0611.jpg,0128.jpg
user_hash,,,,,,,,,,,,,,,,,,,,,
2u7T5g3WNhXLNt8eXLm7iYrvR872,4.0,5.0,5.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3mHQgTNdhoXXOWEsJmHvbBuOxSb2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4jQ4QWrm9SOsFMLIAajSZ5Usva82,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5HBSsBrc7LSwIQyRgTqY7Zf641f2,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
69AHmihCRKbJbXXM9GQ4FT7NSU32,5.0,4.0,2.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [40]:
ratings_df.to_csv('ratings_per_user.csv')

In [41]:
ratings_df['Group'] = ratings_df.index.map(ratings)
ratings_df.dropna(inplace=True)
len(ratings_df)

42

In [42]:
splitted_dataframes = {}
# split dataframes by group
for group in ratings_df['Group'].unique():
    group_df = ratings_df.loc[ratings_df['Group'] == group].copy()
    group_df.drop(columns=['Group'], inplace=True)
    group_df = group_df.loc[:, (group_df != 0).any(axis=0)]
    splitted_dataframes[group] = group_df

In [43]:
group_0_df = splitted_dataframes[0]
group_1_df = splitted_dataframes[1]
group_2_df = splitted_dataframes[2]
group_3_df = splitted_dataframes[3]
group_4_df = splitted_dataframes[4]

In [44]:
group_4_df

,0071.jpg,0351.jpg,0001.jpg,0558.jpg,0081.jpg,0448.jpg,0249.jpg,0734.jpg,0353.jpg,0083.jpg,...,0215.jpg,0697.jpg,0545.jpg,0693.jpg,0356.jpg,0650.jpg,0535.jpg,0382.jpg,0611.jpg,0128.jpg
user_hash,,,,,,,,,,,,,,,,,,,,,
7atSgfmCF7ZvgnM9qSbSoEFikfD2,1.0,1.0,1.0,0.0,1.0,0.0,5.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
JiwrisF5l4QrhHXCKj90Qk2032G2,4.0,1.0,1.0,1.0,1.0,1.0,2.0,0.0,1.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
aVeHsZYwcfc9eCoptpmrL5u6Yd43,1.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
edwmE4aFFtRQfYX1RzNbumGVbok1,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0
jbm4Isok8iU3ygjXAzIEeTbVHVm2,4.0,1.0,1.0,0.0,1.0,1.0,4.0,0.0,1.0,5.0,...,1.0,1.0,0.0,5.0,1.0,0.0,0.0,0.0,0.0,1.0

In [45]:
group_0_df.to_csv('group_0.csv')
group_1_df.to_csv('group_1.csv')
group_2_df.to_csv('group_2.csv')
group_3_df.to_csv('group_3.csv')
group_4_df.to_csv('group_4.csv')